// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apaiwmvjugoauwdnemvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYWl3bXZqdWdvYXV3ZG5lbXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzg1NjYsImV4cCI6MjA2MTk1NDU2Nn0.BlyKOm68sGjqthKTKZgQ77ajftmpDrh2ns9Y2Wq5TSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);